### ISSUE TITLE
Upgrade to Python3

### ISSUE THREAD

**Issue by mec07** [mec07/PyLATO#2]
This repo really needs to be updated to python3. It shouldn't take too long. The .circleci/config.yml file will have to be updated too.

There is even a handy tool to help with this: http://python3porting.com/2to3.html

**Comment by horsfielda** [comment]
Dear Marc,

Do you need me to do this, or are you happy to do it?  I agree with the idea of migrating to python 3.

Andrew

Sent from my BlackBerry DTEK50

**Comment by mec07** [comment]
Hi @horsfielda,

Thanks for responding to this and offering to help (I didn't realise that you would get a notification of this issue!). Your help is always appreciated.

Migrating to python3 is important; however, if I were to rank outstanding tasks on PyLATO by importance, adding black box tests would be the highest importance. I'll make an issue for that now.

Today I've started on adding CI (in this case automated tests and test coverage) which is essential for any modern software project. It's still in the `total-energy` branch, but hopefully I'll finish that today. Another modern software practice is code reviews, so if you are open to it, then we could review each other's pull requests. I can send you a code review request once I've finished updating the `total-energy` branch, how does that sound? Thanks Andrew!

All the best,

Marc

**Comment by mec07** [comment]
@horsfielda The black box tests issue is: #4

**Comment by horsfielda** [comment]
Hi Marc,

I just got an email from GitHub, and was wondering if you needed me to do 
something. Thank you for explaining what is going on.

I have not worked with Pylato for some time, so I am not sure how much I could 
do right now. I also have my hands full with Plato which is undergoing some big 
rewrites. But if you think there is something that it would be very helpful for 
me to do, then I will try to make time for that.

I am of course happy for you to make whatever changes you want. As you have 
added so much to the code, I view it as yours now.

Andrew
-- 
*---------------------------------------------------*
    Andrew Horsfield      a.horsfield@imperial.ac.uk
    Department of Materials, Imperial College London
      South Kensington Campus, London SW7 2AZ, U.K.
              Phone:+44-(0)20-7594-6753
*---------------------------------------------------*

**Comment by mec07** [comment]
Hi Andrew,

Thanks. That's OK, I understand that you're busy right now. I'll still ask
for a code review of the changes once their ready, but I might merge it
anyway. That way you can see the changes in bite sized chunks and get an
idea of the changes that are happening. Maybe you can then export some of
these modern software development practices to PLATO. I really wish that I
had known about unit tests, black box tests, coverage and automating the
running of tests before I started writing PyLATO!

All the best,

Marc

**Comment by mec07** [comment]
Done by PR #10
